### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by ottob** [nazarnovak/mind#1]
It seems like the glue javascript has some kind of reconnect feature. Can you see if you can get it to work?

What I tried to do was this:
1. start server
2. connect with two browsers to an existing case
3. restart server
4. post new message in one of the browsers

I expected the new message to show up in both browsers, but nothing happened.

**Comment by nazarnovak** [comment]
I've confirmed the issue, and added an extra socket listener on reconnecting to the server  
I followed your scenario and with the fix it works now  

There is however another issue: if WS server will be offline, the messages users send will be lost, now that is something I'm not very sure how to fix and if that is important now? I assume some sort of a queue or something
